[build]
  command = "npm run build"
  publish = "dist"

# For SPA routing - all routes go to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Explicitly enable form detection
[build.processing]
  skip_processing = false 